const batmanEspied = [
        {imdbID: 'tt0096895',description:"The Dark Knight of Gotham City begins his war on crime with his first major enemy being Jack Napier, a criminal who becomes the clownishly homicidal Joker.", Title: 'Batman', Year: '1989', Poster: 'https://c4.wallpaperflare.com/wallpaper/117/891/681/robert-pattinson-the-batman-2021-movies-artwork-batman-hd-wallpaper-preview.jpg'},
        {imdbID: 'tt0468569',description:"When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.", Title: 'The Dark Knight', Year: '2008', Poster: 'https://c4.wallpaperflare.com/wallpaper/563/14/336/batman-dark-night-wallpaper-preview.jpg'},
        {imdbID: 'tt2975590',description:"Fearing that the actions of Superman are left unchecked, Batman takes on the Man of Steel, while the world wrestles with what kind of a hero it really needs.", Title: 'Batman v Superman: Dawn of Justice', Year: '2016', Poster: 'https://c4.wallpaperflare.com/wallpaper/701/18/448/batman-vs-superman-fan-art-superman-vs-batman-poster-wallpaper-preview.jpg'},
        {imdbID: 'tt1345836',description:"Eight years after the Joker's reign of anarchy, Batman, with the help of the enigmatic Catwoman, is forced from his exile to save Gotham City from the brutal guerrilla terrorist Bane.", Title: 'The Dark Knight Rises', Year: '2012', Poster: 'https://c4.wallpaperflare.com/wallpaper/573/137/309/batman-bane-catwoman-the-dark-knight-wallpaper-preview.jpg'},
        {imdbID: 'tt0372784',description:"After training with his mentor, Batman begins his fight to free crime-ridden Gotham City from corruption.", Title: 'Batman Begins', Year: '2005', Poster: 'https://www.murphysmultiverse.com/wp-content/uploads/2022/02/Begins-800x450.jpg'},
        {imdbID: 'tt4116284',description:"A cooler-than-ever Bruce Wayne must deal with the usual suspects as they plan to rule Gotham City, while discovering that he has accidentally adopted a teenage orphan who wishes to become his sidekick.", Title: 'The LEGO Batman Movie', Year: '2017', Poster: 'https://c4.wallpaperflare.com/wallpaper/747/244/26/4k-8k-animation-the-lego-batman-movie-wallpaper-preview.jpg'},
        {imdbID: 'tt0112462',description:"Batman must battle former district attorney Harvey Dent, who is now Two-Face and Edward Nygma, The Riddler with help from an amorous psychologist and a young circus acrobat who becomes his sidekick, Robin.", Title: 'Batman Forever', Year: '1995', Poster: 'https://c4.wallpaperflare.com/wallpaper/238/929/184/video-game-batman-forever-wallpaper-preview.jpg'},
        {imdbID: 'tt0118688',description:"Batman and Robin try to keep their relationship together even as they must stop Mr. Freeze and Poison Ivy from freezing Gotham City.", Title: 'Batman & Robin', Year: '1997', Poster: 'https://c4.wallpaperflare.com/wallpaper/554/18/549/batman-batman-and-robin-robin-dc-comics-wallpaper-preview.jpg'},
        {imdbID: 'tt0103776',description:"While Batman deals with a deformed man calling himself the Penguin wreaking havoc across Gotham with the help of a cruel businessman, a female employee of the latter becomes the Catwoman with her own vendetta.", Title: 'Batman Returns', Year: '1992', Poster: 'https://c4.wallpaperflare.com/wallpaper/782/618/388/batman-batman-return-to-arkham-wallpaper-preview.jpg'}
    ];

export function getMovies() {
    return (batmanEspied);
}